version: "3"

services:
    nginx:    
     build: ./www/nginx
     container_name: nginx-container  
     ports: 
      - "80:80"   
     volumes:  
      - ./www/nginx/default.conf:/etc/nginx/default.conf
      - ./www:/var/www/html
      - ./www/php/:/usr/share/nginx/html
    php:    
     build: ./www/php/  
     container_name: php-container  
     ports:
      - "9000:9000"  
     #links:  
     # - mysql  
     volumes:  
      - ./www/php:/home/www/root/
      - ./www/php/php.ini:/usr/local/etc/php/php.ini
      - ./www/php:/usr/share/nginx/html

    mysql:    
     image: mysql:5.7
     container_name: mysql-container  
     volumes:  
      - ./www/mysql/data:/var/lib/mysql
      - ./www/mysql/my.conf:/etc/mysql/conf.d/my.conf
      - ./www/mysql/init:/docker-entrypoint-initdb.d/
     ports: 
      - "3306:3306"
     environment:  
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: www  
      MYSQL_USER: user  
      MYSQL_PASSWORD: 123456  