version: "3"

services:
    nginx:    
     build: ./www/nginx
     container_name: nginx-container  
     ports: 
      - "80:80"   
     volumes:
      - ./www/nginx:/var/www/html
      
    mysql:    
     build: ./www/mysql
     container_name: mysql-container  
     volumes:  
      - ./www/mysql/data:/var/lib/mysql
      - ./www/mysql/init:/docker-entrypoint-initdb.d/
     ports: 
      - "3306:3306"
     environment:  
      MYSQL_ROOT_PASSWORD: 123456  
      MYSQL_USER: root1
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: www
      
    php:    
     build: ./www/nginx/php/
     container_name: php-container  
     ports:
      - "9000:9000"  
     #links:  
     # - mysql  
     volumes:  
      - ./www/nginx/php/php.ini:/usr/local/etc/php.ini
      - ./www/nginx/php:/usr/share/nginx/html
      - ./www/nginx/php:/etc/php
